//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionTarget) DeepCopyInto(out *ActionTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionTarget.
func (in *ActionTarget) DeepCopy() *ActionTarget {
	if in == nil {
		return nil
	}
	out := new(ActionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalWorkspace) DeepCopyInto(out *AdditionalWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalWorkspace.
func (in *AdditionalWorkspace) DeepCopy() *AdditionalWorkspace {
	if in == nil {
		return nil
	}
	out := new(AdditionalWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticGate) DeepCopyInto(out *AgenticGate) {
	*out = *in
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(RetryPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticGate.
func (in *AgenticGate) DeepCopy() *AgenticGate {
	if in == nil {
		return nil
	}
	out := new(AgenticGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactPointer) DeepCopyInto(out *ArtifactPointer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactPointer.
func (in *ArtifactPointer) DeepCopy() *ArtifactPointer {
	if in == nil {
		return nil
	}
	out := new(ArtifactPointer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttemptRef) DeepCopyInto(out *AttemptRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttemptRef.
func (in *AttemptRef) DeepCopy() *AttemptRef {
	if in == nil {
		return nil
	}
	out := new(AttemptRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomatedGate) DeepCopyInto(out *AutomatedGate) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(RetryPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomatedGate.
func (in *AutomatedGate) DeepCopy() *AutomatedGate {
	if in == nil {
		return nil
	}
	out := new(AutomatedGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BacklogItem) DeepCopyInto(out *BacklogItem) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BacklogItem.
func (in *BacklogItem) DeepCopy() *BacklogItem {
	if in == nil {
		return nil
	}
	out := new(BacklogItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BacklogRef) DeepCopyInto(out *BacklogRef) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BacklogRef.
func (in *BacklogRef) DeepCopy() *BacklogRef {
	if in == nil {
		return nil
	}
	out := new(BacklogRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Branch) DeepCopyInto(out *Branch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Branch.
func (in *Branch) DeepCopy() *Branch {
	if in == nil {
		return nil
	}
	out := new(Branch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutSpec) DeepCopyInto(out *CheckoutSpec) {
	*out = *in
	if in.Sparse != nil {
		in, out := &in.Sparse, &out.Sparse
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutSpec.
func (in *CheckoutSpec) DeepCopy() *CheckoutSpec {
	if in == nil {
		return nil
	}
	out := new(CheckoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextPointer) DeepCopyInto(out *ContextPointer) {
	*out = *in
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(ArtifactPointer)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextPointer.
func (in *ContextPointer) DeepCopy() *ContextPointer {
	if in == nil {
		return nil
	}
	out := new(ContextPointer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeterministicRun) DeepCopyInto(out *DeterministicRun) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeterministicRun.
func (in *DeterministicRun) DeepCopy() *DeterministicRun {
	if in == nil {
		return nil
	}
	out := new(DeterministicRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorInfo) DeepCopyInto(out *ErrorInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorInfo.
func (in *ErrorInfo) DeepCopy() *ErrorInfo {
	if in == nil {
		return nil
	}
	out := new(ErrorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalRef) DeepCopyInto(out *ExternalRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalRef.
func (in *ExternalRef) DeepCopy() *ExternalRef {
	if in == nil {
		return nil
	}
	out := new(ExternalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	if in.BlockingPRs != nil {
		in, out := &in.BlockingPRs, &out.BlockingPRs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gaggle) DeepCopyInto(out *Gaggle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gaggle.
func (in *Gaggle) DeepCopy() *Gaggle {
	if in == nil {
		return nil
	}
	out := new(Gaggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Gaggle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleIsolation) DeepCopyInto(out *GaggleIsolation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleIsolation.
func (in *GaggleIsolation) DeepCopy() *GaggleIsolation {
	if in == nil {
		return nil
	}
	out := new(GaggleIsolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleList) DeepCopyInto(out *GaggleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Gaggle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleList.
func (in *GaggleList) DeepCopy() *GaggleList {
	if in == nil {
		return nil
	}
	out := new(GaggleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GaggleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleSandbox) DeepCopyInto(out *GaggleSandbox) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleSandbox.
func (in *GaggleSandbox) DeepCopy() *GaggleSandbox {
	if in == nil {
		return nil
	}
	out := new(GaggleSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleSibling) DeepCopyInto(out *GaggleSibling) {
	*out = *in
	in.Project.DeepCopyInto(&out.Project)
	if in.RequireLabels != nil {
		in, out := &in.RequireLabels, &out.RequireLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleSibling.
func (in *GaggleSibling) DeepCopy() *GaggleSibling {
	if in == nil {
		return nil
	}
	out := new(GaggleSibling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleSpec) DeepCopyInto(out *GaggleSpec) {
	*out = *in
	in.Project.DeepCopyInto(&out.Project)
	in.Backlog.DeepCopyInto(&out.Backlog)
	out.Isolation = in.Isolation
	if in.AdditionalRepos != nil {
		in, out := &in.AdditionalRepos, &out.AdditionalRepos
		*out = make([]RepoRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CICommand != nil {
		in, out := &in.CICommand, &out.CICommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredCapabilities != nil {
		in, out := &in.RequiredCapabilities, &out.RequiredCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunControls != nil {
		in, out := &in.RunControls, &out.RunControls
		*out = new(RunControls)
		**out = **in
	}
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(GaggleSandbox)
		**out = **in
	}
	if in.Workcopies != nil {
		in, out := &in.Workcopies, &out.Workcopies
		*out = new(GaggleWorkcopies)
		**out = **in
	}
	if in.RequireLabels != nil {
		in, out := &in.RequireLabels, &out.RequireLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Siblings != nil {
		in, out := &in.Siblings, &out.Siblings
		*out = make([]GaggleSibling, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleSpec.
func (in *GaggleSpec) DeepCopy() *GaggleSpec {
	if in == nil {
		return nil
	}
	out := new(GaggleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleStatus) DeepCopyInto(out *GaggleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleStatus.
func (in *GaggleStatus) DeepCopy() *GaggleStatus {
	if in == nil {
		return nil
	}
	out := new(GaggleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GaggleWorkcopies) DeepCopyInto(out *GaggleWorkcopies) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GaggleWorkcopies.
func (in *GaggleWorkcopies) DeepCopy() *GaggleWorkcopies {
	if in == nil {
		return nil
	}
	out := new(GaggleWorkcopies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gate) DeepCopyInto(out *Gate) {
	*out = *in
	if in.Automated != nil {
		in, out := &in.Automated, &out.Automated
		*out = new(AutomatedGate)
		(*in).DeepCopyInto(*out)
	}
	if in.Agentic != nil {
		in, out := &in.Agentic, &out.Agentic
		*out = new(AgenticGate)
		(*in).DeepCopyInto(*out)
	}
	if in.Human != nil {
		in, out := &in.Human, &out.Human
		*out = new(HumanGate)
		(*in).DeepCopyInto(*out)
	}
	if in.Branches != nil {
		in, out := &in.Branches, &out.Branches
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gate.
func (in *Gate) DeepCopy() *Gate {
	if in == nil {
		return nil
	}
	out := new(Gate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Goober) DeepCopyInto(out *Goober) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Goober.
func (in *Goober) DeepCopy() *Goober {
	if in == nil {
		return nil
	}
	out := new(Goober)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Goober) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberList) DeepCopyInto(out *GooberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Goober, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberList.
func (in *GooberList) DeepCopy() *GooberList {
	if in == nil {
		return nil
	}
	out := new(GooberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRun) DeepCopyInto(out *GooberRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRun.
func (in *GooberRun) DeepCopy() *GooberRun {
	if in == nil {
		return nil
	}
	out := new(GooberRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooberRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunAction) DeepCopyInto(out *GooberRunAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunAction.
func (in *GooberRunAction) DeepCopy() *GooberRunAction {
	if in == nil {
		return nil
	}
	out := new(GooberRunAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooberRunAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunActionList) DeepCopyInto(out *GooberRunActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GooberRunAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunActionList.
func (in *GooberRunActionList) DeepCopy() *GooberRunActionList {
	if in == nil {
		return nil
	}
	out := new(GooberRunActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooberRunActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunActionSpec) DeepCopyInto(out *GooberRunActionSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunActionSpec.
func (in *GooberRunActionSpec) DeepCopy() *GooberRunActionSpec {
	if in == nil {
		return nil
	}
	out := new(GooberRunActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunActionStatus) DeepCopyInto(out *GooberRunActionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunActionStatus.
func (in *GooberRunActionStatus) DeepCopy() *GooberRunActionStatus {
	if in == nil {
		return nil
	}
	out := new(GooberRunActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunList) DeepCopyInto(out *GooberRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GooberRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunList.
func (in *GooberRunList) DeepCopy() *GooberRunList {
	if in == nil {
		return nil
	}
	out := new(GooberRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooberRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunSpec) DeepCopyInto(out *GooberRunSpec) {
	*out = *in
	in.Workflow.DeepCopyInto(&out.Workflow)
	out.Trigger = in.Trigger
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(RepositoryIdentity)
		**out = **in
	}
	if in.RunControls != nil {
		in, out := &in.RunControls, &out.RunControls
		*out = new(RunControls)
		**out = **in
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]ArtifactPointer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunSpec.
func (in *GooberRunSpec) DeepCopy() *GooberRunSpec {
	if in == nil {
		return nil
	}
	out := new(GooberRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberRunStatus) DeepCopyInto(out *GooberRunStatus) {
	*out = *in
	if in.Attempts != nil {
		in, out := &in.Attempts, &out.Attempts
		*out = make([]AttemptRef, len(*in))
		copy(*out, *in)
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(PauseOccurrence)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberRunStatus.
func (in *GooberRunStatus) DeepCopy() *GooberRunStatus {
	if in == nil {
		return nil
	}
	out := new(GooberRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooberSpec) DeepCopyInto(out *GooberSpec) {
	*out = *in
	if in.HarnessOptions != nil {
		in, out := &in.HarnessOptions, &out.HarnessOptions
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyActions != nil {
		in, out := &in.PolicyActions, &out.PolicyActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConditionalPolicyActions != nil {
		in, out := &in.ConditionalPolicyActions, &out.ConditionalPolicyActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Workflows != nil {
		in, out := &in.Workflows, &out.Workflows
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooberSpec.
func (in *GooberSpec) DeepCopy() *GooberSpec {
	if in == nil {
		return nil
	}
	out := new(GooberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanGate) DeepCopyInto(out *HumanGate) {
	*out = *in
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanGate.
func (in *HumanGate) DeepCopy() *HumanGate {
	if in == nil {
		return nil
	}
	out := new(HumanGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRef) DeepCopyInto(out *InstanceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRef.
func (in *InstanceRef) DeepCopy() *InstanceRef {
	if in == nil {
		return nil
	}
	out := new(InstanceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Limits) DeepCopyInto(out *Limits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limits.
func (in *Limits) DeepCopy() *Limits {
	if in == nil {
		return nil
	}
	out := new(Limits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCredentialRef) DeepCopyInto(out *MCPCredentialRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCredentialRef.
func (in *MCPCredentialRef) DeepCopy() *MCPCredentialRef {
	if in == nil {
		return nil
	}
	out := new(MCPCredentialRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialRefs != nil {
		in, out := &in.CredentialRefs, &out.CredentialRefs
		*out = make([]MCPCredentialRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Manifest) DeepCopyInto(out *Manifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Manifest.
func (in *Manifest) DeepCopy() *Manifest {
	if in == nil {
		return nil
	}
	out := new(Manifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Manifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestList) DeepCopyInto(out *ManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Manifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestList.
func (in *ManifestList) DeepCopy() *ManifestList {
	if in == nil {
		return nil
	}
	out := new(ManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSpec) DeepCopyInto(out *ManifestSpec) {
	*out = *in
	out.Instance = in.Instance
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]Connection, len(*in))
		copy(*out, *in)
	}
	if in.Gaggles != nil {
		in, out := &in.Gaggles, &out.Gaggles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSpec.
func (in *ManifestSpec) DeepCopy() *ManifestSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationEvidenceRef) DeepCopyInto(out *NotificationEvidenceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationEvidenceRef.
func (in *NotificationEvidenceRef) DeepCopy() *NotificationEvidenceRef {
	if in == nil {
		return nil
	}
	out := new(NotificationEvidenceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationFact) DeepCopyInto(out *NotificationFact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationFact.
func (in *NotificationFact) DeepCopy() *NotificationFact {
	if in == nil {
		return nil
	}
	out := new(NotificationFact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSinkRef) DeepCopyInto(out *NotificationSinkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSinkRef.
func (in *NotificationSinkRef) DeepCopy() *NotificationSinkRef {
	if in == nil {
		return nil
	}
	out := new(NotificationSinkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSource) DeepCopyInto(out *NotificationSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSource.
func (in *NotificationSource) DeepCopy() *NotificationSource {
	if in == nil {
		return nil
	}
	out := new(NotificationSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parallel) DeepCopyInto(out *Parallel) {
	*out = *in
	if in.Branches != nil {
		in, out := &in.Branches, &out.Branches
		*out = make([]Branch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parallel.
func (in *Parallel) DeepCopy() *Parallel {
	if in == nil {
		return nil
	}
	out := new(Parallel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PauseOccurrence) DeepCopyInto(out *PauseOccurrence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PauseOccurrence.
func (in *PauseOccurrence) DeepCopy() *PauseOccurrence {
	if in == nil {
		return nil
	}
	out := new(PauseOccurrence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinnedWorkflow) DeepCopyInto(out *PinnedWorkflow) {
	*out = *in
	if in.GraphRef != nil {
		in, out := &in.GraphRef, &out.GraphRef
		*out = new(ArtifactPointer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinnedWorkflow.
func (in *PinnedWorkflow) DeepCopy() *PinnedWorkflow {
	if in == nil {
		return nil
	}
	out := new(PinnedWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessConditions) DeepCopyInto(out *ReadinessConditions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessConditions.
func (in *ReadinessConditions) DeepCopy() *ReadinessConditions {
	if in == nil {
		return nil
	}
	out := new(ReadinessConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationBrief) DeepCopyInto(out *RemediationBrief) {
	*out = *in
	in.GatherPRContext.DeepCopyInto(&out.GatherPRContext)
	if in.GatherCIFailures != nil {
		in, out := &in.GatherCIFailures, &out.GatherCIFailures
		*out = new(RemediationCIFailures)
		(*in).DeepCopyInto(*out)
	}
	if in.GatherReviewThreads != nil {
		in, out := &in.GatherReviewThreads, &out.GatherReviewThreads
		*out = new(RemediationReviewThreads)
		(*in).DeepCopyInto(*out)
	}
	if in.GatherSiblingContext != nil {
		in, out := &in.GatherSiblingContext, &out.GatherSiblingContext
		*out = new(RemediationSiblingContext)
		(*in).DeepCopyInto(*out)
	}
	if in.GatherIssueContext != nil {
		in, out := &in.GatherIssueContext, &out.GatherIssueContext
		*out = new(RemediationIssueContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationBrief.
func (in *RemediationBrief) DeepCopy() *RemediationBrief {
	if in == nil {
		return nil
	}
	out := new(RemediationBrief)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationCIAnnotation) DeepCopyInto(out *RemediationCIAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationCIAnnotation.
func (in *RemediationCIAnnotation) DeepCopy() *RemediationCIAnnotation {
	if in == nil {
		return nil
	}
	out := new(RemediationCIAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationCIFailure) DeepCopyInto(out *RemediationCIFailure) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make([]RemediationCIAnnotation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationCIFailure.
func (in *RemediationCIFailure) DeepCopy() *RemediationCIFailure {
	if in == nil {
		return nil
	}
	out := new(RemediationCIFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationCIFailures) DeepCopyInto(out *RemediationCIFailures) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]RemediationCIFailure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationCIFailures.
func (in *RemediationCIFailures) DeepCopy() *RemediationCIFailures {
	if in == nil {
		return nil
	}
	out := new(RemediationCIFailures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationInlineComment) DeepCopyInto(out *RemediationInlineComment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationInlineComment.
func (in *RemediationInlineComment) DeepCopy() *RemediationInlineComment {
	if in == nil {
		return nil
	}
	out := new(RemediationInlineComment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationIssue) DeepCopyInto(out *RemediationIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationIssue.
func (in *RemediationIssue) DeepCopy() *RemediationIssue {
	if in == nil {
		return nil
	}
	out := new(RemediationIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationIssueContext) DeepCopyInto(out *RemediationIssueContext) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]RemediationIssue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationIssueContext.
func (in *RemediationIssueContext) DeepCopy() *RemediationIssueContext {
	if in == nil {
		return nil
	}
	out := new(RemediationIssueContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationNativeReview) DeepCopyInto(out *RemediationNativeReview) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationNativeReview.
func (in *RemediationNativeReview) DeepCopy() *RemediationNativeReview {
	if in == nil {
		return nil
	}
	out := new(RemediationNativeReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPRContext) DeepCopyInto(out *RemediationPRContext) {
	*out = *in
	if in.Verdict != nil {
		in, out := &in.Verdict, &out.Verdict
		*out = new(Verdict)
		(*in).DeepCopyInto(*out)
	}
	if in.Comments != nil {
		in, out := &in.Comments, &out.Comments
		*out = make([]RemediationThreadComment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPRContext.
func (in *RemediationPRContext) DeepCopy() *RemediationPRContext {
	if in == nil {
		return nil
	}
	out := new(RemediationPRContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationReviewThreads) DeepCopyInto(out *RemediationReviewThreads) {
	*out = *in
	if in.Reviews != nil {
		in, out := &in.Reviews, &out.Reviews
		*out = make([]RemediationNativeReview, len(*in))
		copy(*out, *in)
	}
	if in.InlineComments != nil {
		in, out := &in.InlineComments, &out.InlineComments
		*out = make([]RemediationInlineComment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationReviewThreads.
func (in *RemediationReviewThreads) DeepCopy() *RemediationReviewThreads {
	if in == nil {
		return nil
	}
	out := new(RemediationReviewThreads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSibling) DeepCopyInto(out *RemediationSibling) {
	*out = *in
	if in.OverlappingFiles != nil {
		in, out := &in.OverlappingFiles, &out.OverlappingFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSibling.
func (in *RemediationSibling) DeepCopy() *RemediationSibling {
	if in == nil {
		return nil
	}
	out := new(RemediationSibling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSiblingContext) DeepCopyInto(out *RemediationSiblingContext) {
	*out = *in
	if in.PullRequests != nil {
		in, out := &in.PullRequests, &out.PullRequests
		*out = make([]RemediationSibling, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSiblingContext.
func (in *RemediationSiblingContext) DeepCopy() *RemediationSiblingContext {
	if in == nil {
		return nil
	}
	out := new(RemediationSiblingContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationThreadComment) DeepCopyInto(out *RemediationThreadComment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationThreadComment.
func (in *RemediationThreadComment) DeepCopy() *RemediationThreadComment {
	if in == nil {
		return nil
	}
	out := new(RemediationThreadComment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoRef) DeepCopyInto(out *RepoRef) {
	*out = *in
	if in.Checkout != nil {
		in, out := &in.Checkout, &out.Checkout
		*out = new(CheckoutSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoRef.
func (in *RepoRef) DeepCopy() *RepoRef {
	if in == nil {
		return nil
	}
	out := new(RepoRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIdentity) DeepCopyInto(out *RepositoryIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIdentity.
func (in *RepositoryIdentity) DeepCopy() *RepositoryIdentity {
	if in == nil {
		return nil
	}
	out := new(RepositoryIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunControls) DeepCopyInto(out *RunControls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunControls.
func (in *RunControls) DeepCopy() *RunControls {
	if in == nil {
		return nil
	}
	out := new(RunControls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunTrigger) DeepCopyInto(out *RunTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunTrigger.
func (in *RunTrigger) DeepCopy() *RunTrigger {
	if in == nil {
		return nil
	}
	out := new(RunTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	if in.Run != nil {
		in, out := &in.Run, &out.Run
		*out = new(DeterministicRun)
		(*in).DeepCopyInto(*out)
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContextFrom != nil {
		in, out := &in.ContextFrom, &out.ContextFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyActions != nil {
		in, out := &in.PolicyActions, &out.PolicyActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredCapabilities != nil {
		in, out := &in.RequiredCapabilities, &out.RequiredCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(RetryPolicy)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(Limits)
		**out = **in
	}
	if in.ExpectedOutputs != nil {
		in, out := &in.ExpectedOutputs, &out.ExpectedOutputs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputsFrom != nil {
		in, out := &in.InputsFrom, &out.InputsFrom
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Outbox != nil {
		in, out := &in.Outbox, &out.Outbox
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trigger) DeepCopyInto(out *Trigger) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trigger.
func (in *Trigger) DeepCopy() *Trigger {
	if in == nil {
		return nil
	}
	out := new(Trigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TutorScope) DeepCopyInto(out *TutorScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TutorScope.
func (in *TutorScope) DeepCopy() *TutorScope {
	if in == nil {
		return nil
	}
	out := new(TutorScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Verdict) DeepCopyInto(out *Verdict) {
	*out = *in
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]ArtifactPointer, len(*in))
		copy(*out, *in)
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Verdict.
func (in *Verdict) DeepCopy() *Verdict {
	if in == nil {
		return nil
	}
	out := new(Verdict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workflow) DeepCopyInto(out *Workflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workflow.
func (in *Workflow) DeepCopy() *Workflow {
	if in == nil {
		return nil
	}
	out := new(Workflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowList) DeepCopyInto(out *WorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowList.
func (in *WorkflowList) DeepCopy() *WorkflowList {
	if in == nil {
		return nil
	}
	out := new(WorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowRequirements) DeepCopyInto(out *WorkflowRequirements) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowRequirements.
func (in *WorkflowRequirements) DeepCopy() *WorkflowRequirements {
	if in == nil {
		return nil
	}
	out := new(WorkflowRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowSpec) DeepCopyInto(out *WorkflowSpec) {
	*out = *in
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]Trigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Readiness = in.Readiness
	if in.RunControls != nil {
		in, out := &in.RunControls, &out.RunControls
		*out = new(RunControls)
		**out = **in
	}
	if in.DocsRoots != nil {
		in, out := &in.DocsRoots, &out.DocsRoots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TutorScope != nil {
		in, out := &in.TutorScope, &out.TutorScope
		*out = new(TutorScope)
		**out = **in
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = new(WorkflowRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]Gate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parallels != nil {
		in, out := &in.Parallels, &out.Parallels
		*out = make([]Parallel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowSpec.
func (in *WorkflowSpec) DeepCopy() *WorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowSpec)
	in.DeepCopyInto(out)
	return out
}
